FROM ubuntu:latest
RUN apt-get update && apt-get install -y python3 python3-pip curl wget
COPY app.py /app/app.py
RUN pip3 install flask --break-system-packages
EXPOSE 5000
USER root
CMD ["python3", "/app/app.py"]
